### ISSUE TITLE
File naming problems for lagrangian particle fields

### ISSUE THREAD

**Issue by wyldckat** [blueCFD/Core#1]
In `$FOAM_SRC/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.T.C` we can find this line ([example](https://github.com/blueCFD/OpenFOAM-dev/blob/ed34509ec74aadb29e98a15b5136dedce69aaed8/src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.T.C#L379)):

```
this->name() + ":UCoeff"
```

This is a rather big problem, because the colon symbol is an illegal character for file names in Windows. And furthermore, this is a very usual convention in OpenFOAM:

```
find $FOAM_SRC -name "*.C" -type f | xargs grep ' + ":'
```

will provide a lot of entries where this is used.

As an example, WinSCP translates the file name in accordance to the HTML convention for special characters, i.e. `%3A` is the semi-colon symbol.

It would also be useful if we were able to convert between the two conventions (Windows vs Linux), as well as being able to handle _case sensitivity_ for letters... since we currently use the convention of doing any necessary renaming on a solver by solver basis.

Practical example: the tutorial(s) that use `icoUncoupledKinematicParcelDyMFoam`.

**Comment by wyldckat** [comment]
The other detail is that it would be useful to be able to keep OpenFOAM's source code the way it is, given that these file names with colons can show up from anywhere.

Therefore, the objective is to implement an automated or semi-automated renaming mechanism that
takes advantage of Symscape's implementation for on-the-fly file renaming. For example:

  * The method [`IOobject::replaceFileName`](https://github.com/blueCFD/OpenFOAM-dev/blob/ed34509ec74aadb29e98a15b5136dedce69aaed8/src/OpenFOAM/db/IOobject/IOobject.C#L316) already provides this feature for manual control.

  * This is for example used in file [applications/solvers/basic/potentialFoam/createFields.H](https://github.com/blueCFD/OpenFOAM-dev/blob/ed34509ec74aadb29e98a15b5136dedce69aaed8/applications/solvers/basic/potentialFoam/createFields.H#L1):

  ```
  #if defined( WIN32 ) || defined( WIN64 )
  // Rename Phi to Phi_ to prevent name clashes on Windows with phi
  IOobject::replaceFileName("Phi", "Phi_");
  #endif
  ```

Therefore, it would be useful to extend this feature to something that is at least somewhat automated and not simply having to hard-code all renames.

**Comment by wyldckat** [comment]
There is also the possibility of using a function object for cases on Windows, which would do this kind of renaming based on regular expressions, instead of it being hard-coded anywhere on the solvers or libraries.
The advantage of this is that people would have better control over the file renaming convention, depending on their necessities.

**Comment by wyldckat** [comment]
There is another possibility on how to handle at least the files that have colons: we can create a folder and place those files inside the folder.

For example, `thermo:psi` is a valid field field that OpenFOAM uses for simulations with compressible flow, which means that we could instead create the folder/file `thermo/psi`, so that the actual name structure is well preserved. Problem might be if there ever comes a situation where an already existing name is used, such as `uniform/psi`, leading to potential file name collision with already existing files.

The other possibility would be to *drop down* the colons and get `thermo..psi` instead.

As for upper case letters:

  * `Phi` vs `phi` could be sorted out by using a separate folder for upper case letters, e.g. `UpperCase/Phi`;
  * or prefix those names with two dots: `..Phi` - which would be akin to using `:Phi` for the global namespace.

**Comment by wyldckat** [comment]
Another situation where these names give problems was reported here: http://www.cfd-online.com/Forums/openfoam-pre-processing/175425-file-name-colons-invalid-windows-os.html

Specifically, when running the tutorial case `heatTransfer/chtMultiRegionSimpleFoam/multiRegionHeaterRadiation`, when creating the folder `coarse:Air`.

**Comment by wyldckat** [comment]
I forgot to write here that it was suggested to simply replace the colons for a single dot: https://www.cfd-online.com/Forums/openfoam-solving/175288-file-creation-problem-windows.html#post618365

**Comment by wyldckat** [comment]
In OpenFOAM-dev was recently introduced a mechanism where it automatically looks for `.orig` files when the actual files are missing. It might be a good idea to piggyback on this change for this issue as well.

**Comment by lorenzotrevisan** [comment]
can You please point out the link of the mentioned introduced mechanism for .orig looking?

**Comment by wyldckat** [comment]
@lorenzotrevisan Many thanks for offering to look into this and my apologies for not having answered yet to the PM you sent me.

The commits for `.orig` are as follows:
* https://github.com/OpenFOAM/OpenFOAM-dev/commit/df6e2da2dd89227cee05c0bc0c1bf4f9b80849d5
* https://github.com/OpenFOAM/OpenFOAM-dev/commit/fde4c4f43bc61a09b555af023a7f210086b6cca5
* https://github.com/OpenFOAM/OpenFOAM-dev/commit/1e4f0e06a9d68fb14f0b9f6f2f195dd91c10b8c2

**Comment by wyldckat** [comment]
I've done a bit more researching into how we might be able to preserve a good similarity for file names between Linux and Windows and here is what I've found:

1. We could replace colons `:` with a Unicode alternative, as indicated here: https://stackoverflow.com/a/25477235

2. Similarly, we could potentially replace upper case letters in names to use Unicode instead, but this is assuming that Windows will not still rely on case-preserving methodology that it usually uses.

Another problem is to figure out how exactly to create files with unicode characters in their names, from within our port code.

**Comment by lorenzotrevisan** [comment]
if  You try to create a new empty file from the BlueCFD terminal (MSYS2 console) with colons in the name, it work fine and mswindows show it as a centered squared point that if i copy and paste here it is read as "";
In this way BlueCFD-Core can read start files with colon ":" in the name without problem;
the problem is when the solver try to write results with colon ":" in the file name.
I am not expert of mswindows UNIX porting and i do not have a root access on a mswindows pc (only not privileged user at office, fortunately with BlueCFD-core now) , but i suppose that if You implement the same write mechanism of MSYS2, is should work.

In general (about mswindows filename limitation) i think that a reliable solution should be by using HDF format that seems to permit UNIX file and directory naming into one file; please let see the following conversation: https://stackoverflow.com/questions/22125778/how-is-hdf5-different-from-a-folder-with-files

If You find some interesting way to go, please let me know which approach to explore. 
Ciao

**Comment by wyldckat** [comment]
@lorenzotrevisan Excellent, many thanks! That's essentially the Unicode form of the hexadecimal number for the colon ":", with `F03A` in Unicode and `3A` in UTF8!

Git should also be able to handle Unicode names as well, so with a bit of luck we can use Unicode to tell apart file names with different case letters, e.g. "K" from "k", which would sort out all of the problems in a single go.

Many thanks once again!

**Comment by wyldckat** [comment]
After thinking about this for ages now, my conclusion is that the best solution is to go literal:
* `K` -> `upper_K`
* `kEpsilon:G` -> `kEpsilon_colon_G`

This way we don't have issues with craziness related to using Unicode.

Now it's a matter of coding this in... where:
1. Names with colons will be renamed automatically internally, without manual intervention.
2. As for upper case letters, I'm not sure yet... perhaps using a function object would be best, at least for the time being and it would allow people to choose their own names if necessary.

**Comment by lorenzotrevisan** [comment]
dear Bruno, but [UNIX] kEpsilon:G then should become [MS] k_upper_Epsilon_colon_upper_G ?

other ideas could be (??):
[UNIX] K -> [MS] KKK = kkk
[UNIX] kEpsilon:G -> kEEEpsilon..GGG = keeepsilon..ggg

**Comment by wyldckat** [comment]
Hi Lorenzo,

Sorry, no... no, the idea is to keep the confusion down to a minimum. There are very few situations where the lower and upper case letters collide in case files, e.g. `b` vs `B` and `k` vs `K`, at least as far as I've seen over the years.

Hence the idea to keep the changes to a minimum, as if this was LaTeX mathematical formulation or the LibreOffice equation editor ([for example, see the command words used here](https://help.libreoffice.org/Math/Unary_and_Binary_Operators)), where we use a modifier/operator as a command word where deemed necessary. The underscores merely act as space-character replacements.

Duplicating letters could lead to massive confusion, specially where on Windows users don't give much attention to the details and can easily add one too many letters or not add enough letters.

The two dots as replacement of a colon - `kEpsilon..G` - are not acceptable, due to an internal naming convention in OpenFOAM in interpreting the files with dots in them. The idea is that there is a mathematical/nomenclature convention that is meant to be preserved and the two dots could unravel to an illegal name structure.

Furthermore, if a case doesn't even need the lower and upper case file names, then we don't even use the `upper_` naming convention, hence the reason for using function objects for these situations where renaming files is on-a-need-basis-only.

On the other hand, the usage of `_colon_` to replace `: ` would be enforced on Windows.

**Comment by lorenzotrevisan** [comment]
dear Bruno,
your choice seems to be the Ockham's razor (very KISS)

if i can contribute i'm at Your disposal
ciao
