### ISSUE TITLE
How to compile new solve using blueCFD 2017

### ISSUE THREAD

**Issue by haibianshifeng** [blueCFD/Core#103]
Hi guy

Many Thanks for your effort about providing an alternative, the OpenFOAM can be used on Windows.

I am very delightful for finding some other solve on the github (https://github.com/blueCFD), It imply that BlueCFD can compile new solve.

I found a new solve about Direct simulation Monte Carlo(DSMC) from the github (https://github.com/vincentcasseau/hyStrath). It very helpful for my Ph.D thesis.

When I compile it on BlueCFD 2017, the error appears.

So I want to know how to change it for compiling it on BlueCFD2017!

Many Thanks for your help.

**Comment by wyldckat** [comment]
Quick answer: Building custom code with blueCFD-Core is explained here: https://github.com/blueCFD/Core/wiki/Loose-notes-on-building-custom-code

**Comment by haibianshifeng** [comment]
Many Thanks for your help.
