### ISSUE TITLE
BlueCFD 2017 with GPU

### ISSUE THREAD

**Issue by haibianshifeng** [blueCFD/Core#104]
I have a question.

BlueCFD 2017 can use GPU?

**Comment by wyldckat** [comment]
Well... no and yes... what I mean is:

* There is currently no known or supported capabilities in blueCFD-Core 2017 to work with GPUs for running simulations in parallel.

* In principle, the solutions listed here: https://openfoamwiki.net/index.php/GPGPU - could all potentially work with blueCFD-Core, although the adaptation of the changes needed may not be straight forward. PARALUTION is the most likely the one that may work better with blueCFD-Core, but we haven't ever tested it.
