### ISSUE TITLE
blueCFD-Core-2017-fireFoam-smallPoolFire3D

### ISSUE THREAD

**Issue by MyilsamyDinesh** [blueCFD/Core#105]
Hello, everyone, I am a beginner to OpenFoam, recently I have installed blueCFDcore2017 on my windows computer to practice OpenFOAM. Initially, I was practising tutorials. My research is fire and combustion hence I am focusing to practice OpenFoam. 
I have tried to create my own geometry based on the tutorial file "smallPoolFire3D" but my simulation fails to predict the combustion. However, the tutorial file simulation has no issue.
Except for the vertices and mesh in the blockMeshDict input file, I didn't change any other parameter or another input files. 
Could someone help me to know why I couldn't simulate the fire for my geometry? 
For your more detailed information, I have attached
![tutorial](https://user-images.githubusercontent.com/40662080/42031066-e5b71be6-7b0f-11e8-9288-5a3a08b988c3.jpg)
![my_temp_prediction](https://user-images.githubusercontent.com/40662080/42031067-e5e2e992-7b0f-11e8-91af-b4b373d666fb.jpg)

 the prediction image of tutorial and my geometry

**Comment by wyldckat** [comment]
Quick answer: I suspect that the positions of the original mesh and your mesh are too different, resulting in the source of the flame to be in the wrong location. In other words, the original flame is outside of your mesh.

**Comment by MyilsamyDinesh** [comment]
Thanks, wyldckat I will check with that once again!
