### ISSUE TITLE
Correct atmospheric flow boundary conditions, fvSchemes and fvSolution

### ISSUE THREAD

**Issue by Mattiads1** [blueCFD/Core#109]
Hi, I'm traying to simulate a full developed atm flow into a duct without obstacles. (RANS, simpleFoam, k-epsilon)
I want to fix a vertical inlet profile for U,k and epsilon, and these profiles must be costant along the duct.
I started and modifided the turbineSiting tutorial and I tested diferrent posssibility:
-  the atmBoundaryLayerInlet class functions, for U, k and epsilon, and their respective wall function
- groovyBC at the inlet, by imposing the verticals profiles,with respective wall function and not
also I tryed to mix the atmBoundaryLayerInlet class functions and groovyBC.
but no one of these work well.
The other problem is to set correct discretization schemes and solution. I need of a second order discretization and I tryed to apply  what is in the literature, but many simulations that I tested don't reach the convergence.
There is anyone that can help me? some advice?

**Comment by wyldckat** [comment]
Sorry, but this is the wrong place to ask these questions. Please use the forums at CFD-Online.com: https://www.cfd-online.com/Forums/openfoam/
