### ISSUE TITLE
Fail to compile cfmesh on blueCFD-Core-2017

### ISSUE THREAD

**Issue by LeeLeong** [blueCFD/Core#113]
Hi Bruno Santos,

I try to compile cfmesh on blueCFD-Core-2017 5.x-478c685b424c using link from https://github.com/blueCFD/Core/wiki/Building-cfMesh-with-blueCFD-Core#building-with-bluecfd-core-2017 .
I run into problem step 6th.  Please find the log file in the attachment folder.
[log.make.gz](https://github.com/blueCFD/Core/files/2504767/log.make.gz)

Thank you in advance.

**Comment by wyldckat** [comment]
Hi @LeeLeong,

I've confirmed that the version you are using is blueCFD-Core 2017-2, many thanks for the complete version hash!

Because the reason why it failed to compile is because it is using the full path to the `cfMesh` folder, namely `C:/Program Files/blueCFD-Core-2017/msys64/home/ofuser/cfMesh`, which in the terminal it should be the path `~/cfMesh`.

But if the instructions from https://github.com/blueCFD/Core/wiki/Building-cfMesh-with-blueCFD-Core#building-with-bluecfd-core-2017 - are strictly followed, then this issue should not have occurred, given the instructions aim to place the `cfMesh` folder at the `~/blueCFD/ofuser-of5`, namely `C:\Program Files\blueCFD-Core-2017\ofuser-of5`.

So my guess is that you've downloaded manually the cfMesh package instead of using the git command?

----

**Possibility A**: If this was the reason why you've placed it the `ofuser` home folder, then my request is that you please try the following steps:

1. Open a new the blueCFD-Core terminal.

2. Run the following commands:

    ```
    mkdir -p $FOAM_RUN
    user
    explorer .
    ```

    Note: There is a space character and then a dot symbol at the end of the 3rd command, just in case it's not visible.

3. Windows Explorer should have opened onto the folder `C:\Program Files\blueCFD-Core-2017\ofuser-of5`

4. Place the downloaded package into this folder.

5. Go back to the terminal window and do the same steps you've done in the past for unpacking and compiling it.

----

**Possibility B**: If by any chance you've used the `git clone` command in the default home folder because the `user` command have failed in the past, please let me know, but if this was indeed the situation, then please run the following commands inside the terminal:

```
mkdir -p $FOAM_RUN
user
```

And it should work properly.

Best regards,
Bruno

**Comment by LeeLeong** [comment]
Hi Bruno,

Thanks for attend to my problem.  Indeed I am using the instruction from
https://github.com/blueCFD/Core/wiki/Building-cfMesh-with-blueCFD-Core#building-with-bluecfd-core-2017
. Therefore, I choose the solution of possibility B and it works.
Following your explaination, I found out I some how do not clone the cfMesh
inside 'user" home directory.  The only thing I can say is maybe I do not
login to "user" account.  But i remember I follow exactly the instruction.
Anyway, thank you very much for the help.  I attached here the log file of
the compilation progress.

Thanks ya.

Leong

**Comment by wyldckat** [comment]
I see... looks like I need to improve the description of the command `user`.

The command `user` is an _alias_ command. If you run the following command:

```
alias user
```

you will get the following output:

```
alias user='cd $WM_PROJECT_USER_DIR'
```

So when we run the command:

```
user
```

if will run the associated alias command:

```
cd $WM_PROJECT_USER_DIR
```

which will then go into the folder `/home/ofuser/blueCFD/ofuser-of5` on its own.

As a side note, the username `ofuser` is the default username blueCFD-Core always uses within the terminal, which means that everyone is sort-of logged into it by default. This was done to avoid having usernames with special characters or spaces in said name.

Many thanks for your feedback on this and I'll add this information to the FAQ (Frequently Asked Questions) page, along with links to it whenever we mention the command `user` when working on the next milestone.

**Comment by LeeLeong** [comment]
I appreciate your effort making this available to all of us.  Thank you
very much.

**Comment by LeeLeong** [comment]
Hi Bruno,

By following your guide in here
https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-v1712/CentOS_SL_RHEL
and
http://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-6/CentOS_SL_RHEL
, I am able to compile ESI-OpenFOAM from source on Centos 7.5.

I would to say thank you very much to you for providing good compiling
instructions.  I would like to share with you the compiling command.  It
may not the best compiling method.

# Compile OpenfOAM-v1806

cd /opt
mkdir OpenFOAM
cd OpenFOAM
ls

yum groupinstall 'Development Tools'

yum install openmpi openmpi-devel zlib-devel gstreamer-plugins-base-devel
libXext-devel libGLU-devel libXt-devel libXrender-devel libXinerama-devel
libpng-devel libXrandr-devel libXi-devel libXft-devel libjpeg-turbo-devel
libXcursor-devel readline-devel ncurses-devel python python-devel cmake
qt-devel qt-assistant mpfr-devel gmp-devel

yum -y install mesa-libGLU mesa-libGLU-devel mesa-libOSMesa-devel

yum upgrade

wget
https://sourceforge.net/projects/openfoamplus/files/v1806/OpenFOAM-v1806.tgz

wget
https://sourceforge.net/projects/openfoamplus/files/v1806/ThirdParty-v1806.tgz

tar -xzf OpenFOAM-v1806.tgz
tar -xzf ThirdParty-v1806.tgz

ls

cd ThirdParty-v1806
ln -s ParaView-v5.5.2/VTK VTK-9.0.0

mkdir download

wget -P download https://www.cmake.org/files/v3.9/cmake-3.9.0.tar.gz
wget -P download
https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.1.tar.bz2
wget -P download
http://download.qt.io/official_releases/qt/5.9/5.9.3/single/qt-everywhere-opensource-src-5.9.3.tar.xz
wget -P download ftp://ftp.freedesktop.org/pub/mesa/mesa-17.0.0.tar.xz

tar -xzf download/cmake-3.9.0.tar.gz
tar -xjf download/openmpi-2.1.1.tar.bz2
tar -xf download/qt-everywhere-opensource-src-5.9.3.tar.xz
tar -xf download/mesa-17.0.0.tar.xz

cd ..

nedit /opt/OpenFOAM/OpenFOAM-v1806/etc/bashrc
line 41,42,43 comment out
line 44, uncomment
line 85, WM_MPLIB=SYSTEMOPENMPI -> WM_MPLIB=OPENMPI

nedit /opt/OpenFOAM/OpenFOAM-v1806/etc/config.sh/mpi
line 59,  FOAM_MPI=openmpi-1.10.4  -->  export FOAM_MPI=openmpi-2.1.1

nedit /opt/OpenFOAM/OpenFOAM-v1806/etc/config.sh/paraview
line 50,  ParaView_QT=qt-system   --> ParaView_QT=qt-5.9.3
line 51,  cmake_version=cmake-system  -->  cmake_version=cmake-3.9.0

nedit /opt/OpenFOAM/OpenFOAM-v1806/etc/config.sh/vtk
line 35,  mesa_version=mesa-17.1.1   --> mesa_version=mesa-17.0.0

nedit /opt/OpenFOAM/ThirdParty-v1806/makeVTK.example
line 8,  mesa=mesa-17.1.1   --> mesa=mesa-17.0.0

nedit /opt/OpenFOAM/ThirdParty-v1806/makeParaView.example
line 8,  mesa=mesa-17.1.1   --> mesa=mesa-17.0.0
line 19, add,    -qmake
/opt/OpenFOAM/ThirdParty-v1806/platforms/linux64Gcc/qt-5.9.3 \

*                 -qt \
source /opt/OpenFOAM/OpenFOAM-v1806/etc/bashrc  WM_LABEL_SIZE=64
WM_NCOMPPROCS=cpu_number WM_MPLIB=OPENMPI
echo "alias of1806='source /opt/OpenFOAM/OpenFOAM-v1806/etc/bashrc
$FOAM_SETTINGS'" >> $HOME/.bashrc

exit

su -

of1806

cd $WM_THIRD_PARTY_DIR

./makeCmake cmake-3.9.0 > log.makeCmake 2>&1
wmRefresh

./makeOPENMPI > log.makeOPENMPI 2>&1
wmRefresh

./makeQt qt-everywhere-opensource-src-5.9.3 > log.makeQt 2>&1
wmRefresh

./makeMesa > log.makeMesa 2>&1
wmRefresh

./makeVTK.example  > log.makeVTK 2>&1
wmRefresh

./Allwmake > log.make 2>&1
wmRefresh

# compile paraview without GUI.

./makeParaView.example > log.makeParaview 2>&1
wmRefresh

# since we compile with paraview prefix, the system could not find the path
of the paraview as set in $WM_PROJECT_DIR/etc/config.sh/paraview line 112,
make a link to the paraview folder.
ln -s /platforms/linux64Gcc/ParaView-5.5.2-mesa-mpi-py ParaView-5.5.2

cd $WM_PROJECT_DIR

./Allwmake -j cpu_number > log.make 2>&1
mv log.make log.make_1st

./Allwmake -j cpu_number > log.make 2>&1
mv log.make log.make_2nd

* To lunch Paraview server

mpirun -np cpu_number pvserver

Best regards,
Leong

**Comment by wyldckat** [comment]
Hi Leong,

Many thanks for sharing, but the correct location for sharing that information is in a new thread at https://www.cfd-online.com/Forums/openfoam-installation/

Best regards,
Bruno
