### ISSUE TITLE
cfMesh crashes

### ISSUE THREAD

**Issue by novicefoamer** [blueCFD/Core#114]
The cfMesh crashes without completing the mesh, it works when the cell size is higher, but when the cell size is higher, the geometry doesn't close, when I reduce the cell size, the cfmesh crashes I have included the log file in this email.

[log.txt](https://github.com/blueCFD/Core/files/2558383/log.txt)

**Comment by wyldckat** [comment]
In the log file is the following entry:

```
ZN4Foam6sigFpe13sigFpeHandlerEi
```

A `sigFpe` indicates a Floating Point Error (FPE), usually related to a division by zero or any other similar mathematical operation.

Perhaps the STL file has an illegal triangle (area = 0) and that is why `tetMesh.exe` fails? Have you checked with the utility `surfaceCheck`?

**Comment by novicefoamer** [comment]
I have checked with surfaceCheck, there are no illegal triangles. I have included it in this email, I can share the mesh file with you.
[logCheck.txt](https://github.com/blueCFD/Core/files/2576880/logCheck.txt)

**Comment by wyldckat** [comment]
8% of the triangles have low quality (first row on the Triangle quality array), which may or may not be a problem.

But there is a clear indication that there is more than one object inside the STL file:

```
Writing zoning to "zone_Fuselage5.vtk"...

writing part 0 size 1674 to "Fuselage5_0.obj"
writing part 1 size 24016 to "Fuselage5_1.obj"

Number of zones (connected area with consistent normal) : 2
More than one normal orientation.
```

Therefore, it makes sense that it's not able to close the geometry, given that there is more than one object...

Beyond this, there is no clear indication of this being a bug in our port of cfMesh to Windows, therefore it falls in the category of _user support_, for which this issue tracker was not created for.

If you need free support in using cfMesh, I suggest that you go to the dedicated forum: https://www.cfd-online.com/Forums/openfoam-community-contributions/?pp=40&daysprune=-1&prefixid=openfoam_cc_cfmesh

**Comment by novicefoamer** [comment]
Oh okay, thank you! Yeah, I have reached out to Creative Fields for paid support, just wanted to know where the problem would be. Thank you for the support!
