### ISSUE TITLE
Heat Release Rate Prediction issues in OpenFoam 5.x

### ISSUE THREAD

**Issue by DineshMyilsamy** [blueCFD/Core#115]
I am a graduate student who is trying to learn fireFoam for my research purpose. Recently I was practising smallPoolFire3D tutorial in fireFoam. In order to find the heat release rate, I tried the following command by imposing it on my controlDict file but it doesn't work. I am requesting for your help to calculate the heat release rate in fireFoam (OpenFoam version 5.x)

HRR
 {
 type cellSource;
 functionObjectLibs ("libfieldFunctionObjects.so");
 enabled true;
writeControl timeStep; //outputTime;
writeInterval 1;
 log false;
 valueOutput false;
 source all; //cellZone;
 sourceName c0;
 operation volIntegrate;
 fields
 (
 dQ
 );
}

**Comment by wyldckat** [comment]
The correct location for your question is at the CFD-Online forums: https://www.cfd-online.com/Forums/openfoam-solving/
