### ISSUE TITLE
Installing Gmsh in blueCFD 

### ISSUE THREAD

**Issue by Razon007** [blueCFD/Core#148]
Hi all,
I just installed blueCFD 2017-2 and trying to add Gmsh with blueCFD but unable to do it. I tried a couple of times by following the instruction given in the website.

http://bluecfd.github.io/Core/FAQ/how-to-install-additional-software-such-as-gmsh/

The problem is that Gnuplot did not install with blueCFD version 2017-2. I have installed several times but no improvement. I did even checked the custom installation but there wasn't any file for Gnuplot. 
Can anyone help me to resolve this issue? Thanks in advance..

Cheers
Razon

**Comment by Razon007** [comment]
> 
> 
> Hi all,
> I just installed blueCFD 2017-2 and trying to add Gmsh with blueCFD but unable to do it. I tried a couple of times by following the instruction given in the website.
> 
> http://bluecfd.github.io/Core/FAQ/how-to-install-additional-software-such-as-gmsh/
> 
> The problem is that Gnuplot did not install with blueCFD version 2017-2. I have installed several times but no improvement. I did even checked the custom installation but there wasn't any file for Gnuplot.
> Can anyone help me to resolve this issue? Thanks in advance..
> 
> Cheers
> Razon

Any help regarding this issue?

**Comment by wyldckat** [comment]
Greetings Razon,

Sorry for the delay, but I've been having some fairly hectic days lately...

Instead of the `gnuplot.sh` file, you can use the `notepad2.sh`.

As for Gnuplot, the version that is installed is no longer as an addon, it's installed directly with MSys2, which is why it's not present in the `bashrc.d` folder.

Best regards,
Bruno

**Comment by Razon007** [comment]
> 
> 
> Greetings Razon,
> 
> Sorry for the delay, but I've been having some fairly hectic days lately...
> 
> Instead of the `gnuplot.sh` file, you can use the `notepad2.sh`.
> 
> As for Gnuplot, the version that is installed is no longer as an addon, it's installed directly with MSys2, which is why it's not present in the `bashrc.d` folder.
> 
> Best regards,
> Bruno

Hi Bruno, 
Thank you very much for your useful comments. I have done it as you told and its working now. The problem is solved.

Cheers
Razon

**Comment by Razon007** [comment]
The problem is resolved....
