### ISSUE TITLE
fatal error: cstdint: No such file or directory  #include <cstdint>

### ISSUE THREAD

**Issue by Flopi76** [blueCFD/Core#149]
I tried to compile a new solver and I have this error message. I'm not sure what it means especially since other solvers get compiled properly.
Any thoughts ?

**Comment by wyldckat** [comment]
That's extremely vague... starting by: Where did the `#include <cstdint>` even come from? Is it in the new solver code? And if so, was it tested on Linux?

Because the only thing that comes to mind is that the code you are trying to compile is relying on another C++ standard, such as C++11 or C++14??

**Comment by Flopi76** [comment]
Well, that's the thing, I started that new solver by copying an old one. I didn't change anything else in the settings or in the dependencies.
The #include<cstdint> comes from a long list of dependencies. Below some more of the error (probably should have added it right away sorry).

In file included from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/lnInclude/int32.H:1:0,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/primitives/ints/int/int.H:38,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/lnInclude/int.H:1,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/primitives/ints/label/label.H:39,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/lnInclude/label.H:1,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/primitives/ints/lists/labelList.H:47,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/lnInclude/labelList.H:1,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H:42,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/db/IOstreams/Pstreams/Pstream.T.H:42,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/lnInclude/Pstream.T.H:1,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/global/argList/parRun.H:35,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/lnInclude/parRun.H:1,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/finiteVolume/cfdTools/general/include/fvCFD.H:4,
                 from C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/finiteVolume/lnInclude/fvCFD.H:1,
                 from Main.c:32:
C:/PROGRA~1/BLUECF~1/OpenFOAM-5.x/src/OpenFOAM/primitives/ints/int32/int32.H:39:10: fatal error: cstdint: No such file or directory
 #include <cstdint>

**Comment by wyldckat** [comment]
The content of the files inside the folder  `Make`, will tell the whole story we are missing here... namely these two:
* `files`
* `options`

The very most critical one is the second one, since it has the compilation options.

The other possibility is that there could be an `#include` somewhere in the solver's code that is interfering with anything else?

**Comment by Flopi76** [comment]
Content of files:

Main.C
EXE = $(FOAM_USER_APPBIN)/Main.C

Content of options:
EXE_INC = \
    -I$(LIB_SRC)/finiteVolume/lnInclude \
    -I$(LIB_SRC)/meshTools/lnInclude

EXE_LIBS = \
    -lfiniteVolume \
    -lfvOptions \
    -lmeshTools

About the other possibility, is there any way to check this?

**Comment by wyldckat** [comment]
Something is very wrong in what you've provided... there are no backslashes `\` in the `options` file and the `EXE`  line in `files` should not have that name at the end...

`Main.C` as a file name is also extremely suspicious... what are the first files of code in it? Namely the `#include` lines and any `#define` lines?

**Comment by Flopi76** [comment]
About the option file, for a reason the \ didn't copy, but they are actually there. 

I renamed the .C file, it was indeed potentially problematic. I also removed the .C from the EXE line of the 'files'. 
The error does not appear anymore... So i guess it was either one or the other.

Thanks for the help
