### ISSUE TITLE
Mean age of air, PPD PMV result in Paraview

### ISSUE THREAD

**Issue by ananddoss2004** [blueCFD/Core#151]
Can someone tell me how to view results of Local mean age of air (LMA) and Predicted mean vote and predicted person dissatisfied  in ParaView ?

**Comment by wyldckat** [comment]
Quick answer: Viewing the results is pretty much the same thing as with every other field in OpenFOAM: once you have the resulting fields from a simulation or post-processing with function objects, you can view the results.

As for calculating those fields, I believe that was only recently implemented in OpenFOAM 8... which we haven't been able to release yet on blueCFD-Core.
