### ISSUE TITLE
Python script is not loading on blueCFD version 2017-2

### ISSUE THREAD

**Issue by Razon007** [blueCFD/Core#152]
Hi all,

First of all thanks for making such a wonderful tool for OpenFOAM users to work with windows environment. However, after installing blueCFD version 2017-2, I have encountered an error regarding the python package. I always try to use the python script for running my case file. Now when I run a python script in blueCFD terminal, it shows an error. The error message shows;

**./thick5mm.sh
Traceback (most recent call last):
  File "turquantity.py", line 1, in <module>
    import numpy as np
ImportError: No module named numpy**

Actually, I think I can understand what the error says here but couldn't resolve this issue so far.  The problem occurs because of the NumPy module which the python package installed with 2017-2 can not load. Can anyone please help me how to resolve this issue? Thank you very much in advance.

Cheers,
Razon

**Comment by wyldckat** [comment]
Quick answer: See issue #128. In this comment is indicated how to install for Python 3: https://github.com/blueCFD/Core/issues/128#issuecomment-520906306
