### ISSUE TITLE
surface scalar field phi missing

### ISSUE THREAD

**Issue by ananddoss2004** [blueCFD/Core#159]
Hi Brunos, Greetings. I tried to use chtMultiRegionFoam for heat transfer analysis. It is able to solve for fluid regions but for solid region it is asking scalar field phi file missing in 0/solid portion. I have attached the 0 folder along with my system file. If you can rectify it will be of great help and its little urgent. The same case file worked for small geometry but for bigger file it is giving this kind of problem which makes me think that it has something to do with solver, just my guess.

FOAM FATAL ERROR:

    request for surfaceScalarField phi from objectRegistry belt_area failed
    available objects of type surfaceScalarField are
0()

    From function const Type& Foam::objectRegistry::lookupObject(const Foam::word&) const [with Type = Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh>]
    in file X:/OpenFOAM-5.x/src/OpenFOAM/db/objectRegistry/objectRegistryTemplates.C at line 193.

FOAM aborting

[Case.zip](https://github.com/blueCFD/Core/files/5294083/Case.zip)

**Comment by wyldckat** [comment]
Quick answers:
1. phi is needed only for fluid flow, which means that you have an incorrect boundary condition or function object for the solid region.

2. When you need urgent support, then a support contract is your best option. We provide at least a 10 hour support package... for more details, feel free to contact us at https://joomla.bluecape.com.pt/index.php?option=com_contact&Itemid=3&lang=en
