### ISSUE TITLE
Trojan found in blueCFD-Core-2017-2

### ISSUE THREAD

**Issue by cgrammens** [blueCFD/Core#184]
I downloaded blueCFD-Core-2017-2-win64-setup.exe on Thursday 11/18 and recently installed to used with Eddy 3D.  My IT manager was alerted that there was a trojan threat.  Below is the information that we have from the Webroot alert.

Threat List:
MTST.EXE, Trojan.Dropper.Gen, %programfiles%\bluecfd-core-2017\thirdparty-5.x\platforms\mingw_w64gccdpint32\scotch_6.0.3\bin\,   
GTST.EXE, Trojan.Dropper.Gen, %programfiles%\bluecfd-core-2017\thirdparty-5.x\platforms\mingw_w64gccdpint32\scotch_6.0.3\bin\,  

Can you look into this threat?  We would like to use Eddy on a few projects and want to make sure this is taken care of prior to distribution to the team.

Thx,
Chris Grammens
BIM Manager
Miller Hull

**Comment by wyldckat** [comment]
Greetings Chris,

Many thanks for this report!
Those two binaries are not used in OpenFOAM's workflow and were compiled with/from the Scotch library source code. You can safely delete that "bin" folder and still use the blueCFD-Core 2017-2 installation without problems.

In the meantime, we have already released blueCFD-Core 2020-1 a few months ago, so you might want to contact the Eddy 3D project for them to update their workflow.

On our side, I will look into having these binaries tested online with a wide variety of antivirus tests, both on the 2017-2 and 2020-1, to check if this is a real threat or merely a similar pattern to an actual trojan/virus.

Best regards,
Bruno

**Comment by wyldckat** [comment]
According to the website Virus Total, those two binaries were tagged only by one of 68 antivirus:
* https://www.virustotal.com/gui/file/28c2942c8a73d0f4f28d99780f4ea020cd331856ea0090bb44b9436a676e0ff5
* https://www.virustotal.com/gui/file/2d24efb6bec87d9d9bbff6967caca63339fd52221ebf7a65e70871c874c84794

I'm currently checking the updated binaries from blueCFD-Core 2020-1...

**Comment by wyldckat** [comment]
From blueCFD-Core 2020-1, the results were:
* https://www.virustotal.com/gui/file/e55a681777caab92b647d933e0b362a322beed5910b038272da6f6e55250d682/detection - none detected for `MTST.EXE`
* https://www.virustotal.com/gui/file/66c65904043aa79654e8e57b2e80049cbce6ab83a9c08129277f74ef3525b378/details - Webroot is the only one once again to detect something suspicious in `GTST.EXE`

I'll try to send a sample of this for re-analysis by Webroot, since this was detected as part of a heuristic detection mechanism for similar file dropping mechanisms.

**Comment by wyldckat** [comment]
I've reported these 3 files as "False Positive detection" to http://snup.webrootcloudav.com/SkyStoreFileUploader/upload.aspx - as they indicate here: https://answers.webroot.com/Webroot/ukp.aspx?pid=17&vw=1&app=vw&solutionid=1839

Either way, you can remove this specific `bin` folder after installing blueCFD-Core. As long as these binaries are not executed, they should not be able to do anything dangerous, if they are at all capable of doing that.

**Comment by cgrammens** [comment]
Thank you for the information and looking into this for us.
