### ISSUE TITLE
blockMesh fails with many errors, is it an installation issue or my geometry is wrong?

### ISSUE THREAD

**Issue by Foadsf** [blueCFD/Core#185]
Following [this](https://www.cfd-online.com/Forums/openfoam/239224-using-openfoam-run-2d-convection-diffusion-simulation-compressible-steady-s.html#post818045) post and the comments on [this](https://stackoverflow.com/q/70256103/4999991) post, I was advised to post my `blockMeshDict` file here

[blockMeshDict.zip](https://github.com/blueCFD/Core/files/7667528/blockMeshDict.zip)

to see if I have an installation problem with blueCFD OpenFOAM package on my non-privileged Windows machine, and/or there are issues with my mesh file. You may see the error messages [here](https://www.cfd-online.com/Forums/openfoam/239224-using-openfoam-run-2d-convection-diffusion-simulation-compressible-steady-s.html#post818045).

**Comment by wyldckat** [comment]
Quick answer: The error message you should be looking at is this one:
```
--> FOAM FATAL ERROR:
face 1 in patch 0 does not have neighbour cell face: 4(12 17 5 0)

    From function Foam::labelList Foam::polyMesh::facePatchFaceCells(const faceList&, const labelListList&, const faceListList&, Foam::label) const
    in file meshes/polyMesh/polyMeshFromShapeMesh.C at line 118.

FOAM aborting
```

The remaining errors/warnings are for helping diagnose where the issue might have come from, but in this situation, they won't be of much use.

To solve this issue, you will need to resort to the isolate-and-conquer strategy: figure out the issues, one block at a time, with patches not explicitly declared at first.

You can confirm if your installation has some kind of issue, if you run the tutorial `basic/potentialFoam/cylinder`, which you can do with the following commands:

```
run
cp -r $FOAM_TUTORIALS/basic/potentialFoam/cylinder .
cd cylinder
./Allrun
```

**Comment by wyldckat** [comment]
Attached is the log file `log.blockMesh` you can expect from running the tutorial I mentioned above:
[log.blockMesh.txt](https://github.com/blueCFD/Core/files/7667627/log.blockMesh.txt)

**Comment by wyldckat** [comment]
Side note: Please don't forget to mention in the [thread at CFD-Online](https://www.cfd-online.com/Forums/openfoam/239224-using-openfoam-run-2d-convection-diffusion-simulation-compressible-steady-s.html#post818045) about this answer.

**Comment by Foadsf** [comment]
the `./Allrun` command finishes with no errors:

<pre>
Running blockMesh on /home/ofuser/cylinder
Running potentialFoam on /home/ofuser/cylinder
Running postProcess on /home/ofuser/cylinder
</pre>

so I assume my blueCFD installation is OK, right?

any idea how I can fix the 

<pre>
--> FOAM FATAL ERROR:
face 1 in patch 0 does not have neighbour cell face: 4(12 17 5 0)

    From function Foam::labelList Foam::polyMesh::facePatchFaceCells(const faceList&, const labelListList&, const faceListList&, Foam::label) const
    in file meshes/polyMesh/polyMeshFromShapeMesh.C at line 118.

FOAM aborting
</pre>

error message? [Here](https://www.cfd-online.com/Forums/openfoam/239224-using-openfoam-run-2d-convection-diffusion-simulation-compressible-steady-s.html#post815127) you may see the schematic representation of my geometry:

<pre>
  <center>
    <img src="https://i.imgur.com/eFXs9DB.png" width="400">
  </center>                  
</pre>

**Comment by wyldckat** [comment]
You can inspect the content of the log file with any of the following commands:
```
nano log.blockMesh
less log.blockMesh
cat log.blockMesh
```

As I explained before, isolate and conquer... you can start by commenting out all patches, e.g., by adding `/*` and `*/` before and after each list:
```
/*
patch1
{
   ....
}

...

patch10
{
   ....
}

*/
```

**Comment by Foadsf** [comment]
I solved part of the problem:
[blockMeshDict.zip](https://github.com/blueCFD/Core/files/7667999/blockMeshDict.zip)

and I have a rough idea of where the rest of the problems are. 
But in the meantime, can you be kind to help me know what this error

<pre>
 cannot load PDB helper DLL
Error occurred with cv2pdb, have stripped binary as a workaround.
</pre>

means? Should I do something about it or just ignore it for now?

**Comment by wyldckat** [comment]
Quick answer: https://github.com/blueCFD/Core/discussions/186

**Comment by Foadsf** [comment]
BTW, @wyldckat  it would be great to have you and the rest of the blueCFD folks in the [OpenFOAM Discord channel](https://discord.gg/5hXCM8K).

**Comment by wyldckat** [comment]
@Foadsf:
1. Given that the channel is named "Elmer", doesn't inspire much confidence in its objective...
2. Discord is too transient and temporary. "Proper" forums are preferred, hence CFD-Online. If anything, a "Discourse" forum mode would be preferable.
3. Last but not least: https://www.cfd-online.com/Forums/blogs/wyldckat/4438-hanging-my-volunteer-gloves-moving-new-phase-my-life.html

**Comment by Foadsf** [comment]
Dear Bruno @wyldckat ,

- There is actually a dedicated Discord server for OpenFOAM [here](https://discord.gg/P9p9eHn) too. 
- I know Discord is far from ideal. But like it or not, a lot of users are already there, Specially the newer generations. 
- About number 3 I totally understand. You have my respect! 🖖
