### ISSUE TITLE
user-complied solver not work for "fvOptions"

### ISSUE THREAD

**Issue by scurryfoam** [blueCFD/Core#32]
ver. = blueCFD-Core-2016-1-win64
os   = windows 10

Issue >>
    New-compiled solvers seems not to recognize model-type in constant/fvOptions.
   This issue can be easily reproduced by compiling rhoReactingFoam in solvers/combustion/reactingFoam. I changed Make/files by "EXE = $(FOAM_USER_APPBIN)/xrhoReactingFoam".
  Then, I run this new-compiled binary for "tutorials\lagrangian\reactingParcelFoam\filter" and error follows;

[message]----------------------------------------------------[start]
Creating finite volume options from "constant/fvOptions"

Selecting finite volume options model type scalarSemiImplicitSource
We're sorry, but the application crashed and safe stack tracing isn't available in this current implementation of blueCFD-Core patches for OpenFOAM.
[message]----------------------------------------------------[end]

**Comment by wyldckat** [comment]
Please try using the following commands to compile your custom solver, by running inside the source code folder for `xrhoReactingFoam`:
```
wclean all
wmake all
wmakeVerifyExeDependencies ./
wmake all
```

`wmakeVerifyExeDependencies` will check what libraries the solver didn't link to and add the missing details, then the last `wmake` will apply the new settings.

Please let us know if this fixes the problem.

**Comment by scurryfoam** [comment]
Surely, "wmakeVerifyExeDependencies" utility is the key.
In the case of user-solvers, I think, this doesn't work.

Test>>
For $WM_PROJECT_DIR/application/solvers/combustion/reactingFoam/rhoReactingFoam, "wmakeVerifyExeDependencies" gives some messages to say re-wmake.
But, for user-directory/rhoReactingFoam, This utility don't produce any message.
(No message means nothing?.....)

**Comment by wyldckat** [comment]
Many thanks for the feedback! There is indeed a bug in the script, which is now fixed on the online repository, as mentioned in the previous two auto-comments.

To apply this fix, you have at least two options, where the simplest one is to run the following commands:
```
foam
cd wmake
wget https://raw.githubusercontent.com/blueCFD/OpenFOAM-dev/blueCFD-Core-4.x/wmake/wmakeVerifyExeDependencies -O wmakeVerifyExeDependencies
```
This will get you the updated script and should fix the problem.

The other option is to get the latest developments and update the build as instructed here: https://github.com/blueCFD/Core/wiki/Quick-notes-on-how-to-update-build - but it will take some considerable time to rebuild from source code :(

As for documenting this, I'll write on the wiki shortly and add to the FAQ.

**Comment by wyldckat** [comment]
* FAQ entry has been added: http://bluecfd.github.io/Core/FAQ/#having-other-problems-with-custom-source-code
 * Wiki page has been added: https://github.com/blueCFD/Core/wiki/Loose-notes-on-building-custom-code

@scurryfoam: I'm closing this report as it is now fixed, but you can still provide more comments on this or even re-open it if necessary!

**Comment by Zeinababosedaira278** [comment]
Hello, I have a problem, when I write the command wmakeVerifyExeDependencies ./
 It gives me the following message: 
**wmakeVerifyExeDependencies error: environment variable $WM_LINK_LANGUAGE not set** 
if anyone can help me with that. Thank you so much

**Comment by wyldckat** [comment]
@Zeinababosedaira278 Please provide more information on the new issue I've opened with your question, namely in issue #243.
