### ISSUE TITLE
Can't use foamMonitor on Windows, due to x11 terminal not existing for gnuplot

### ISSUE THREAD

**Issue by wyldckat** [blueCFD/Core#97]
The solution would be to replace the `x11` entry for `windows` and remove the `noraise persistent` options.

However, this should be made a bit more generic, since there should be an option for exporting to PNG, SVG or any other image format...

**Comment by s1291** [comment]
Currently I solve this by replacing `x11` by `wxt` or some other terminals.

**Comment by Mattiads1** [comment]
Hi,  where are you replaced  x11 by wxt terminal? I have the same problem, can you be more specific?
Thanks

**Comment by s1291** [comment]
@Mattiads1 : In windows, I think the terminal x11 does not exist, instead there are others, for example:
`qt`  Qt cross-platform interactive terminal.
`windows`  Microsoft Windows.
`wxt`  wxWidgets cross-platform interactive terminal.
To see the complete list of the available terminals in gnuplot, open gnuplot and type: `set terminal`
I think you got the idea.

**Comment by wyldckat** [comment]
My apologies for not giving more details on this sooner. I've gotten another question about this a few minutes ago and here are the steps to fix this:

1. Start a new blueCFD-Core terminal.

2. Run the following command:

    ```
    sed -i -e 's=set term x11=set term windows=' -e 's= persist noraise==' $(which foamMonitor)
    ```

3. It should now be fixed and ready to work properly.

**Note**: You can replace the `windows` word in step 2, for `wxt` or `qt`, if you prefer another one.


@s1291: Which of the terminals `qt`, `windows` and `wxt` does it look better to you?

**Comment by s1291** [comment]
@wyldckat : Hello Bruno, Personally I prefer the `wxt` terminal.
Sometimes I change style to make the graphs look better, for e.g, I  change the style of the grid, to get something like this:
![graphe](https://user-images.githubusercontent.com/17838489/43529933-a9772a92-95ac-11e8-99b3-c932c26fd43e.PNG)

**Comment by Mattiads1** [comment]
Thank you for the reply. I have fix the problem
