### ISSUE TITLE
Error calculation of forces and forceCoeffs

### ISSUE THREAD

**Issue by ethren** [blueCFD/Core#98]
Hello I am trying to extract forces and forceCeoffs from an BlueCFD case on windows 7 using
`postProcess -fields "(p,U)" -func forceCoeffs `
but I get the following warnings
```
--> FOAM Warning :
    From function bool Foam::dictionary::add(Foam::entry*, bool)
    in file db/dictionary/dictionary.C at line 884
    Reading ""
    attempt to add entry functions which already exists in dictionary ""
--> FOAM Warning :
    From function static bool Foam::functionObjectList::readFunctionObject(const Foam::string&, Foam::dictionary&, Foam::HashSet<>&, const Foam::word&)
    in file db/functionObjects/functionObjectList/functionObjectList.C at line 246
    Cannot find functionObject file forceCoeffs
```
But without output in the postProcessing folder

**Comment by wyldckat** [comment]
Greetings @ethren,

Are you able to reproduce this error with one of OpenFOAM's tutorial cases?

Best regards,
Bruno

**Comment by ethren** [comment]
Hello Bruno
Sorry, this is actually not an issue because I get the same warning in OpenFOAM 5.x on Ubuntu. I think this is due to the wrong configuration that I made to calculate the force coefficients ...etc
regards

**Comment by wyldckat** [comment]
OK, many thanks for the feedback!
My main concern was that I wasn't certain what were the steps needed for reproducing the error message you had gotten.

**Comment by ethren** [comment]
Dear Bruno, please I have a question that I can't find an answer (I tried on cfd-online but I cannot find an answer):
* If a have a simulation with dynamic mesh, How can I set the liftDir and dragDir directions? Can OpenFOAM detect the direction automatically ? or do I need to create some scripts to deal with that (e.g Python)?

.

**Comment by wyldckat** [comment]
Please create a thread on the OpenFOAM forum  at CFD-Online and post the link to it here, so that it's easier for people in the future to find the same question+answer ;)
